const data = [
  {
    index: "#1",
    latitude: 50.07122048704789,
    longitude: 14.439507755725478,
    name: "Cheesecake time",
    address: "Americká 2, Praha 2",
    category: "cafe",
    categoryName: "Kavárna s koutkem",
    instagram: "https://www.instagram.com/cheesecake.time/",
    facebook: null,
    web: null,
    changingStation: false,
    mat: true,
    barrierFree: true,
    filters: ["mat", "barrier-free", "indoor"]
  },
  {
    index: "#2",
    latitude: 50.087195390774184,
    longitude: 14.429918442472008,
    name: "Hlína (Kampus Hybernská)",
    address: "Hybernská 4, Praha 1",
    category: "cafe",
    categoryName: "Kavárna s koutkem",
    instagram: "https://www.instagram.com/kavarna.hlina/",
    facebook: null,
    web: null,
    changingStation: false,
    mat: true,
    barrierFree: false,
    filters: ["mat", "indoor"]
  },
  {
    index: "#3",
    latitude: 50.027458550759015,
    longitude: 14.59381452678034,
    name: "Block Café",
    address: "K Dálnici 61, Praha 22",
    category: "outdoors",
    categoryName: "Místo s venkovním hřištěm",
    instagram: "https://www.instagram.com/blockuhrineves/",
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: true,
    filters: ["barrier-free", "outdoor"]

  },
  {
    index: "#4",
    latitude: 50.089611715556664,
    longitude: 14.427740253772464,
    name: "Pizza Nuova",
    address: "Revoluční 1, Praha 1",
    category: "restaurant",
    categoryName: "Restaurace s koutkem",
    instagram: "https://www.instagram.com/pizza_nuova/",
    facebook: null,
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: true,
    filters: ["mat", "barrier-free", "changing-station", "indoor"]
  },
  {
    index: "#5",
    latitude: 50.08823250244053,
    longitude: 14.43000132678235,
    name: "Cacao",
    address: "V Celnici 1031/4, Praha 1",
    category: "cafe",
    categoryName: "Kavárna s koutkem",
    instagram: "https://www.instagram.com/cacaoprague/",
    facebook: null,
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ["mat", "changing-station", "indoor"]
  },
  {
    index: "#6",
    latitude: 50.06445215060716,
    longitude: 14.443655115131497,
    name: "Zrno Zrnko",
    address: "Čestmírova 17a, Praha 4",
    category: "cafe",
    categoryName: "Kavárna s koutkem",
    instagram: null,
    facebook: null,
    web: "https://www.zrnozrnko.cz/nusle/",
    changingStation: true,
    mat: false,
    barrierFree: true,
    filters: ["barrier-free", "changing-station", "indoor", "outdoor"]
  },
  {
    index: "#7",
    latitude: 49.99156094071551,
    longitude: 14.660282613284126,
    name: "Říčanský pivovar",
    address: "Olivova 246/23, Říčany",
    category: "outdoors",
    categoryName: "Místo s venkovním hřištěm",
    instagram: "https://www.instagram.com/ricanskypivovar/",
    facebook: null,
    web: null,
    changingStation: true,
    mat: false,
    barrierFree: true,
    filters: ["barrier-free", "changing-station", "outdoor"]
  },
  {
    index: "#8",
    latitude: 50.08272242432239,
    longitude: 14.424635511654554,
    name: "Bazén a bar Juliš",
    address: "Václavské nám. 782, Praha 1",
    category: "cafe",
    categoryName: "Kavárna s koutkem",
    instagram: null,
    facebook: null,
    web: "https://www.bazenjulis.cz/",
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ["mat", "changing-station", "indoor"]
  },
  {
    index: "#9",
    latitude: 50.040303700616526,
    longitude: 14.436052297945764,
    name: "Chaloupka",
    address: "Antala Staška 327/16, Praha 4",
    category: "playroom",
    categoryName: "Herna",
    instagram: null,
    facebook: "https://www.facebook.com/Chaloupkaherna/",
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ["mat", "changing-station", "indoor"]
  },
  {
    index: "#10",
    latitude: 50.023502169759176,
    longitude: 14.605811793368943,
    name: "U Splavu",
    address: "U Nadýmače 200/37, Praha 22",
    category: "outdoors",
    categoryName: "Místo s venkovním hřištěm",
    instagram: null,
    facebook: "https://www.facebook.com/usplavu",
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ["outdoor"]
  }
]

export default data