const data = [
  {
    index: '#1',
    latitude: 50.07122048704789,
    longitude: 14.439507755725478,
    name: 'Cheesecake time',
    address: 'Americká 2, Praha 2',
    category: 'cafe',
    categoryName: 'Kavárna s koutkem',
    instagram: 'https://www.instagram.com/cheesecake.time/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: true,
    barrierFree: false,
    filters: ['mat', 'inside'],
  },
  {
    index: '#2',
    latitude: 50.087195390774184,
    longitude: 14.429918442472008,
    name: 'Hlína (Kampus Hybernská)',
    address: 'Hybernská 4, Praha 1',
    category: 'cafe',
    categoryName: 'Kavárna s koutkem',
    instagram: 'https://www.instagram.com/kavarna.hlina/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: true,
    barrierFree: false,
    filters: ['mat', 'inside'],
  },
  {
    index: '#3',
    latitude: 50.027458550759015,
    longitude: 14.59381452678034,
    name: 'Block Café',
    address: 'K Dálnici 61, Praha 22',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: 'https://www.instagram.com/blockuhrineves/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: true,
    filters: ['barrier-free', 'outside'],
  },
  {
    index: '#4',
    latitude: 50.089611715556664,
    longitude: 14.427740253772464,
    name: 'Pizza Nuova',
    address: 'Revoluční 1, Praha 1',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: 'https://www.instagram.com/pizza_nuova/',
    facebook: null,
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: true,
    filters: ['mat', 'barrier-free', 'changing-station', 'inside'],
  },
  {
    index: '#5',
    latitude: 50.08823250244053,
    longitude: 14.43000132678235,
    name: 'Cacao',
    address: 'V Celnici 1031/4, Praha 1',
    category: 'cafe',
    categoryName: 'Kavárna s koutkem',
    instagram: 'https://www.instagram.com/cacaoprague/',
    facebook: null,
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ['mat', 'changing-station', 'inside'],
  },
  {
    index: '#6',
    latitude: 50.06445215060716,
    longitude: 14.443655115131497,
    name: 'Zrno Zrnko',
    address: 'Čestmírova 17a, Praha 4',
    category: 'cafe',
    categoryName: 'Kavárna s koutkem',
    instagram: null,
    facebook: null,
    web: 'https://www.zrnozrnko.cz/nusle/',
    changingStation: true,
    mat: false,
    barrierFree: true,
    filters: ['barrier-free', 'changing-station', 'inside', 'outside'],
  },
  {
    index: '#7',
    latitude: 49.99156094071551,
    longitude: 14.660282613284126,
    name: 'Říčanský pivovar',
    address: 'Olivova 246/23, Říčany',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: 'https://www.instagram.com/ricanskypivovar/',
    facebook: null,
    web: null,
    changingStation: true,
    mat: false,
    barrierFree: true,
    filters: ['barrier-free', 'changing-station', 'outside'],
  },
  {
    index: '#8',
    latitude: 50.08272242432239,
    longitude: 14.424635511654554,
    name: 'Bazén a bar Juliš',
    address: 'Václavské nám. 782, Praha 1',
    category: 'cafe',
    categoryName: 'Kavárna s koutkem',
    instagram: null,
    facebook: null,
    web: 'https://www.bazenjulis.cz/',
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ['mat', 'changing-station', 'inside'],
  },
  {
    index: '#9',
    latitude: 50.040303700616526,
    longitude: 14.436052297945764,
    name: 'Chaloupka',
    address: 'Antala Staška 327/16, Praha 4',
    category: 'playroom',
    categoryName: 'Herna',
    instagram: null,
    facebook: 'https://www.facebook.com/Chaloupkaherna/',
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: false,
    filters: ['mat', 'changing-station', 'inside'],
  },
  {
    index: '#10',
    latitude: 50.023502169759176,
    longitude: 14.605811793368943,
    name: 'U Splavu',
    address: 'U Nadýmače 200/37, Praha 22',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: null,
    facebook: 'https://www.facebook.com/usplavu',
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['outside'],
  },
  {
    index: '#11',
    latitude: 50.11333838113994,
    longitude: 14.467535088300222,
    name: 'Restaurace Koráb',
    address: 'Krejčího 2261, Praha 8',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: null,
    facebook: null,
    web: 'http://www.restauracekorab.cz/',
    changingStation: true,
    mat: false,
    barrierFree: true,
    filters: ['changing-station', 'barrier-free', 'outside'],
  },
  {
    index: '#12',
    latitude: 50.79137905909804,
    longitude: 15.218751743990376,
    name: 'Hotel Peklo',
    address: 'Josefův Důl 960,  Josefův Důl',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: 'https://www.instagram.com/hotelpeklo/',
    facebook: null,
    web: null,
    changingStation: true,
    mat: true,
    barrierFree: true,
    filters: ['changing-station', 'barrier-free', 'mat', 'outside', 'inside'],
  },
  {
    index: '#13',
    latitude: 50.78789308548892,
    longitude: 15.214508770980332,
    name: 'Perla Jizery',
    address: 'Josefův Důl 187, Josefův Důl',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: 'https://www.instagram.com/hotelperlajizery/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
  {
    index: '#14',
    latitude: 50.79498183137402,
    longitude: 15.163645870980593,
    name: 'Prezidentská chata',
    address: 'Janov nad Nisou 524, Bedřichov',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: 'https://www.instagram.com/prezidentska/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
  {
    index: '#15',
    latitude: 50.02984256207178,
    longitude: 14.604995656107606,
    name: 'Pivovarská Restaurace',
    address: 'K Sokolovně 38, Praha 22',
    category: 'outdoors',
    categoryName: 'Místo s venkovním hřištěm',
    instagram: null,
    facebook: null,
    web: 'https://restaurantpivovarska.cz/',
    changingStation: false,
    mat: false,
    barrierFree: true,
    filters: ['outside', 'barrier-free'],
  },
  {
    index: '#16',
    latitude: 50.049910474417764,
    longitude: 14.440057515130944,
    name: 'Šalanda Pankrác',
    address: 'Na Strži 2097/63,  Praha 4',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: 'https://www.restauracesalanda.cz/cs/salanda/pankrac/',
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: true,
    filters: ['inside', 'barrier-free'],
  },
  {
    index: '#17',
    latitude: 50.07215928149701,
    longitude: 14.436892811441824,
    name: 'Klempírna',
    address: 'Záhřebská 317,  Praha 2',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: null,
    facebook: null,
    web: 'http://www.klempirna-restaurant.cz/',
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
  {
    index: '#18',
    latitude: 50.03086870580955,
    longitude: 14.600757546019874,
    name: 'Čínská Restaurace Dragon',
    address: 'Přátelství 142, Praha 22',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: null,
    facebook: null,
    web: 'https://dragonrestaurace.cz/',
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
  {
    index: '#19',
    latitude: 50.10078366822635,
    longitude: 14.4242013,
    name: 'Bahn Mi Makers',
    address: 'Letenské nám. 5, Praha 7',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: 'https://www.instagram.com/banhmimakers/?hl=cs',
    facebook: null,
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
  {
    index: '#20',
    latitude: 50.10776853213939,
    longitude: 14.453374053972164,
    name: 'Pod Párou',
    address: 'Jankovcova 1037/49, Praha 7',
    category: 'restaurant',
    categoryName: 'Restaurace s koutkem',
    instagram: null,
    facebook: 'https://www.facebook.com/PodParouRestaurace/',
    web: null,
    changingStation: false,
    mat: false,
    barrierFree: false,
    filters: ['inside'],
  },
];

export default data;
